FROM node:18

WORKDIR /app

# Create a volume for node_modules
VOLUME /app/node_modules

# Install dependencies
COPY package*.json ./
RUN npm install

# Expose the development server port
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]